version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "23:00"
  open-pull-requests-limit: 10
  labels:
  - "automerge"
  reviewers:
  - aniskhan001
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "23:00"
  open-pull-requests-limit: 10
  labels:
  - "automerge"
  reviewers:
  - aniskhan001
